"""Tests for the content-based quality gates."""

from stackslice.extract import (
    MAX_FILE_BYTES,
    gate_ansible_role,
    gate_helm_chart,
    gate_manifest_set,
    gate_terraform_module,
)
from tests.test_detect import ANSIBLE_PLAYBOOK, HELM_TEMPLATE, K8S_DEPLOYMENT

CHART_YAML = "apiVersion: v2\nname: api\nversion: 1.2.3\n"
VALUES = "replicaCount: 2\nimage:\n  repository: acme/api\n"
SERVICE_TEMPLATE = (
    "apiVersion: v1\nkind: Service\nmetadata:\n  name: {{ .Release.Name }}\n"
)

TF_MAIN = 'resource "aws_s3_bucket" "b" {\n  bucket = var.name\n}\n'
TF_VARS = 'variable "name" {\n  type = string\n}\n'


def unit(*pairs):
    return [{"relative": name, "content": content} for name, content in pairs]


def test_helm_chart_passes():
    ok, reason, quality = gate_helm_chart(
        unit(
            ("Chart.yaml", CHART_YAML),
            ("values.yaml", VALUES),
            ("templates/deployment.yaml", HELM_TEMPLATE),
            ("templates/service.yaml", SERVICE_TEMPLATE),
        )
    )
    assert ok, reason
    assert quality["templates"] == 2
    assert quality["templated_templates"] == 2


def test_helm_chart_without_values_is_kept_but_flagged():
    """Helm renders fine without values.yaml, so this is richness, not validity."""
    ok, reason, quality = gate_helm_chart(
        unit(
            ("Chart.yaml", CHART_YAML),
            ("templates/a.yaml", HELM_TEMPLATE),
            ("templates/b.yaml", SERVICE_TEMPLATE),
        )
    )
    assert ok, reason
    assert quality["has_values"] is False


def test_helm_chart_rejected_with_one_template():
    ok, reason, _ = gate_helm_chart(
        unit(("Chart.yaml", CHART_YAML), ("values.yaml", VALUES),
             ("templates/only.yaml", HELM_TEMPLATE))
    )
    assert not ok and reason == "too_few_templates"


def test_helm_chart_rejected_when_metadata_is_broken():
    ok, reason, _ = gate_helm_chart(
        unit(("Chart.yaml", "name: [unclosed"), ("values.yaml", VALUES),
             ("templates/a.yaml", HELM_TEMPLATE), ("templates/b.yaml", HELM_TEMPLATE))
    )
    assert not ok and reason == "unparseable_chart_metadata"


def test_helm_chart_rejected_when_nothing_is_templated():
    """A chart whose templates contain no substitutions is a manifest dump."""
    ok, reason, _ = gate_helm_chart(
        unit(("Chart.yaml", CHART_YAML), ("values.yaml", VALUES),
             ("templates/a.yaml", K8S_DEPLOYMENT), ("templates/b.yaml", K8S_DEPLOYMENT))
    )
    assert not ok and reason == "no_templating"


def test_oversized_file_is_rejected():
    ok, reason, _ = gate_helm_chart(
        unit(("Chart.yaml", CHART_YAML), ("values.yaml", "x" * (MAX_FILE_BYTES + 1)),
             ("templates/a.yaml", HELM_TEMPLATE), ("templates/b.yaml", HELM_TEMPLATE))
    )
    assert not ok and reason == "file_too_large"


def test_terraform_module_passes():
    ok, reason, quality = gate_terraform_module(
        unit(("main.tf", TF_MAIN), ("variables.tf", TF_VARS))
    )
    assert ok, reason
    assert quality["tf_files"] == 2
    assert quality["has_variables"]


def test_terraform_module_rejected_without_declarations():
    ok, reason, _ = gate_terraform_module(
        unit(("main.tf", "# empty\n"), ("other.tf", "\n"))
    )
    assert not ok and reason == "no_declarations"


def test_terraform_module_rejected_when_generated():
    generated = "// Code generated by tfgen. DO NOT EDIT.\n" + TF_MAIN
    ok, reason, _ = gate_terraform_module(
        unit(("main.tf", generated), ("vars.tf", generated))
    )
    assert not ok and reason == "generated"


def test_ansible_role_passes():
    ok, reason, quality = gate_ansible_role(
        unit(("tasks/main.yml", ANSIBLE_PLAYBOOK), ("defaults/main.yml", "port: 80\n"))
    )
    assert ok, reason
    assert quality["has_defaults"]


def test_ansible_role_rejected_without_verifiable_tasks():
    ok, reason, _ = gate_ansible_role(
        unit(("tasks/main.yml", "just a string"), ("defaults/main.yml", "port: 80\n"))
    )
    assert not ok and reason == "unverified_tasks"


def test_manifest_set_passes_and_records_kinds():
    service = "apiVersion: v1\nkind: Service\nmetadata:\n  name: api\n"
    ok, reason, quality = gate_manifest_set(
        unit(("deployment.yaml", K8S_DEPLOYMENT), ("service.yaml", service))
    )
    assert ok, reason
    assert quality["manifests"] == 2
    assert quality["kinds"] == ["Deployment", "Service"]


def test_manifest_set_rejects_a_lone_manifest():
    ok, reason, _ = gate_manifest_set(
        unit(("deployment.yaml", K8S_DEPLOYMENT), ("notes.yaml", "a: b\n"))
    )
    assert not ok and reason == "too_few_manifests"


def test_empty_unit_is_rejected():
    for gate in (gate_helm_chart, gate_terraform_module, gate_ansible_role,
                 gate_manifest_set):
        ok, reason, _ = gate([])
        assert not ok and reason == "empty"
