"""Tests for the content-based YAML and file detectors."""

import pytest

from stackslice.detect import (
    YamlKind,
    classify_yaml,
    is_dockerfile,
    is_terraform,
    looks_generated,
)

K8S_DEPLOYMENT = """\
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: api
          image: ghcr.io/acme/api:1.2.3
"""

HELM_TEMPLATE = """\
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
"""

HELM_HELPER = """\
{{- define "api.fullname" -}}
{{- .Chart.Name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
"""

COMPOSE = """\
version: "3.9"
services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
"""

WORKFLOW = """\
name: CI
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
"""

PROM_RULES = """\
groups:
  - name: api
    rules:
      - alert: HighErrorRate
        expr: rate(http_requests_total{code=~"5.."}[5m]) > 0.05
        for: 10m
"""

ANSIBLE_PLAYBOOK = """\
- hosts: webservers
  become: true
  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
"""

ANSIBLE_TASKS = """\
- name: install packages
  ansible.builtin.package:
    name: "{{ item }}"
  with_items: "{{ packages }}"
"""

CLOUDFORMATION = """\
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-bucket
"""

OPENAPI = """\
openapi: 3.0.3
info:
  title: Orders API
  version: 1.0.0
paths:
  /orders:
    get:
      responses:
        "200":
          description: ok
"""

HELM_VALUES = """\
replicaCount: 2
image:
  repository: ghcr.io/acme/api
  tag: 1.2.3
resources:
  limits:
    cpu: 500m
"""

GITLAB_CI = """\
stages:
  - build
  - deploy
build:
  script:
    - make build
"""

LOCALISATION_YAML = """\
en:
  hello: Hello
  goodbye: Goodbye
"""


@pytest.mark.parametrize(
    ("content", "path", "expected"),
    [
        (K8S_DEPLOYMENT, "k8s/deployment.yaml", YamlKind.K8S_MANIFEST),
        (K8S_DEPLOYMENT, "anything/else.yaml", YamlKind.K8S_MANIFEST),
        (HELM_TEMPLATE, "charts/api/templates/deployment.yaml", YamlKind.HELM_TEMPLATE),
        (HELM_TEMPLATE, "somewhere/odd.yaml", YamlKind.HELM_TEMPLATE),
        (COMPOSE, "docker-compose.yml", YamlKind.COMPOSE),
        (WORKFLOW, ".github/workflows/ci.yml", YamlKind.GITHUB_ACTIONS),
        (PROM_RULES, "rules/api.yml", YamlKind.PROMETHEUS_RULES),
        (ANSIBLE_PLAYBOOK, "site.yml", YamlKind.ANSIBLE),
        (ANSIBLE_TASKS, "roles/base/tasks/main.yml", YamlKind.ANSIBLE),
        (CLOUDFORMATION, "template.yaml", YamlKind.CLOUDFORMATION),
        (OPENAPI, "api/openapi.yaml", YamlKind.OPENAPI),
        (HELM_VALUES, "charts/api/values.yaml", YamlKind.HELM_VALUES),
        (GITLAB_CI, ".gitlab-ci.yml", YamlKind.GITLAB_CI),
        (LOCALISATION_YAML, "config/locales/en.yml", YamlKind.OTHER),
    ],
)
def test_classify_yaml(content, path, expected):
    assert classify_yaml(content, path) is expected


def test_helm_templates_are_not_counted_as_manifests():
    """A chart template has apiVersion and kind but is not deployable as-is."""
    assert classify_yaml(HELM_TEMPLATE, "templates/deploy.yaml") is YamlKind.HELM_TEMPLATE
    assert classify_yaml(K8S_DEPLOYMENT, "templates/deploy.yaml") is YamlKind.K8S_MANIFEST


def test_helm_helper_without_kind_is_still_a_template():
    assert classify_yaml(HELM_HELPER, "charts/api/templates/_helpers.tpl") is YamlKind.HELM_TEMPLATE


def test_manifest_detection_survives_multi_document_yaml():
    content = "---\n" + K8S_DEPLOYMENT + "---\n" + COMPOSE
    assert classify_yaml(content, "all.yaml") is YamlKind.K8S_MANIFEST


def test_empty_and_junk_yaml():
    assert classify_yaml("", "x.yaml") is YamlKind.OTHER
    assert classify_yaml("# just a comment\n", "x.yaml") is YamlKind.OTHER


def test_is_terraform():
    assert is_terraform('resource "aws_s3_bucket" "b" {\n  bucket = "x"\n}\n')
    assert is_terraform('module "vpc" {\n  source = "./vpc"\n}\n')
    assert is_terraform("variable \"region\" {\n  type = string\n}\n")
    assert not is_terraform("# just a note about terraform\n")
    assert not is_terraform("")


def test_is_dockerfile():
    assert is_dockerfile("FROM alpine:3.20\nRUN apk add curl\n")
    assert is_dockerfile("# comment\nfrom python:3.12\ncopy . /app\n")
    assert not is_dockerfile("RUN something without a from\n")
    assert not is_dockerfile("")


def test_looks_generated():
    assert looks_generated("# DO NOT EDIT. Generated by protoc.\napiVersion: v1\n")
    assert looks_generated("// Code generated by mockgen. DO NOT EDIT.\n")
    assert not looks_generated(K8S_DEPLOYMENT)


ANSIBLE_ROLE_TEMPLATE = """\
server {
    listen {{ nginx_port }};
    server_name {{ inventory_hostname }};
}
"""


def test_ansible_role_templates_are_not_helm_templates():
    """Jinja in roles/<x>/templates/ must not be misfiled as a chart template."""
    assert classify_yaml(ANSIBLE_ROLE_TEMPLATE, "roles/nginx/templates/site.conf.j2") is not YamlKind.HELM_TEMPLATE
    assert classify_yaml(HELM_TEMPLATE, "roles/x/templates/deploy.yaml") is YamlKind.K8S_MANIFEST


def test_bare_task_list_is_ansible():
    assert classify_yaml(ANSIBLE_TASKS, "roles/base/tasks/main.yml") is YamlKind.ANSIBLE
    assert classify_yaml(ANSIBLE_TASKS, "tasks/install.yml") is YamlKind.ANSIBLE
